/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

// Brand and UI colors for ClarityOS
export const colors = {
	primary: "#ACFF64", // Vibrant green
	background: "#FFFFFF", // White
	surface: "#292929", // Dark surface
	error: "#FF7535", // Error orange
	border: "#E5E5E5", // Light gray border
	text: "#555555", // Main text gray
};
