/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

// Duolingo-inspired color palette
export const duolingoColors = {
	// Primary Brand Colors
	primary: {
		DEFAULT: "#58CC02", // Duolingo Green
		50: "#F0FCE8",
		100: "#DDF9CC",
		200: "#BEF264",
		300: "#8DE639",
		400: "#58CC02",
		500: "#46A302",
		600: "#378002",
		700: "#2D6102",
		800: "#1F4102",
		900: "#132801",
	},

	// Secondary Colors
	secondary: {
		DEFAULT: "#1CB0F6", // Sky Blue
		50: "#E8F8FF",
		100: "#CCF0FF",
		200: "#8DE0FF",
		300: "#4DD0FF",
		400: "#1CB0F6",
		500: "#0B7BC7",
		600: "#064B98",
		700: "#032F69",
		800: "#01183A",
		900: "#000C1B",
	},

	// Accent Colors
	accent: {
		gold: "#FFD900", // Achievement Gold
		orange: "#FF9600", // Energy/Fire
		red: "#FF4B4B", // Hearts/Lives
		purple: "#CE82FF", // Premium/Special
		pink: "#FF82B2", // Friendship/Social
	},

	// Semantic Colors
	success: "#58CC02",
	warning: "#FFD900",
	error: "#FF4B4B",
	info: "#1CB0F6",

	// Neutral Colors
	gray: {
		50: "#F8F9FA",
		100: "#F1F3F4",
		200: "#E8EAED",
		300: "#DADCE0",
		400: "#BDC1C6",
		500: "#9AA0A6",
		600: "#80868B",
		700: "#5F6368",
		800: "#3C4043",
		900: "#202124",
	},
};

// Original colors for backwards compatibility
export const colors = {
	light: {
		background: "hsl(0, 0%, 100%)",
		foreground: "hsl(0, 0%, 14.50%)",
		card: "hsl(0, 0%, 100%)",
		cardForeground: "hsl(0, 0%, 14.50%)",
		popover: "hsl(0, 0%, 100%)",
		popoverForeground: "hsl(0, 0%, 14.50%)",
		primary: "hsl(0, 0%, 20.50%)",
		primaryForeground: "hsl(0, 0%, 98.50%)",
		secondary: "hsl(0, 0%, 97%)",
		secondaryForeground: "hsl(0, 0%, 20.50%)",
		muted: "hsl(0, 0%, 97%)",
		mutedForeground: "hsl(0, 0%, 55.60%)",
		accent: "hsl(0, 0%, 97%)",
		accentForeground: "hsl(0, 0%, 20.50%)",
		destructive: "hsl(0, 80%, 57.70%)",
		destructiveForeground: "hsl(0, 0%, 100%)",
		border: "hsl(0, 0%, 92.20%)",
		input: "hsl(0, 0%, 92.20%)",
		ring: "hsl(0, 0%, 70.80%)",
	},
	dark: {
		background: "hsl(240, 10%, 3.90%)",
		foreground: "hsl(0, 0%, 98%)",
		card: "hsl(240, 10%, 3.90%)",
		cardForeground: "hsl(0, 0%, 98%)",
		popover: "hsl(240, 10%, 3.90%)",
		popoverForeground: "hsl(0, 0%, 98%)",
		primary: "hsl(0, 0%, 98%)",
		primaryForeground: "hsl(240, 5.90%, 10%)",
		secondary: "hsl(240, 3.70%, 15.90%)",
		secondaryForeground: "hsl(0, 0%, 98%)",
		muted: "hsl(240, 3.70%, 15.90%)",
		mutedForeground: "hsl(240, 5%, 64.90%)",
		accent: "hsl(240, 3.70%, 15.90%)",
		accentForeground: "hsl(0, 0%, 98%)",
		destructive: "hsl(0, 62.80%, 30.60%)",
		destructiveForeground: "hsl(0, 85.70%, 97.30%)",
		border: "hsl(240, 3.70%, 15.90%)",
		input: "hsl(240, 3.70%, 15.90%)",
		ring: "hsl(240, 4.90%, 83.90%)",
	},
};
