/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

// Brand colors for ClarityOS
export const brandColors = {
	// Primary Brand Colors - Vibrant ClarityOS palette
	primary: {
		vibrantGreen: "#9AFF9A",
		neonGreen: "#7EFF7E",
		vibrantPink: "#FF69B4",
		hotPink: "#FF1493",
	},

	// Neutral Colors - Clean grays with dark background
	neutrals: {
		darkBackground: "#1A1A1A",
		cardBackground: "#FFFFFF",
		textPrimary: "#000000",
		textSecondary: "#666666",
		iconGray: "#999999",
	},

	// Accent Colors
	accent: {
		yellow: "#FFD700",
		orange: "#FFA500",
	},

	// Semantic Colors
	success: "#9AFF9A", // Vibrant green
	warning: "#FFA500", // Orange
	error: "#FF1493", // Hot pink
	info: "#7EFF7E", // Neon green
};

// Single theme colors
export const colors = {
	background: "#1A1A1A", // Dark background
	foreground: "#FFFFFF", // White text
	card: "#FFFFFF", // White card background
	cardForeground: "#000000", // Black text on cards
	popover: "#FFFFFF",
	popoverForeground: "#000000",
	primary: "#9AFF9A", // Vibrant green
	primaryForeground: "#000000", // Black text on primary
	secondary: "#7EFF7E", // Neon green
	secondaryForeground: "#000000",
	muted: "#666666", // Text secondary
	mutedForeground: "#999999", // Icon gray
	accent: "#FF69B4", // Vibrant pink
	accentForeground: "#FFFFFF",
	destructive: "#FF1493", // Hot pink
	destructiveForeground: "#FFFFFF",
	border: "#666666",
	input: "#666666",
	ring: "#9AFF9A", // Vibrant green
};
